name=INA Series Sensor
version=0.2.5
author=dunknowcoding
maintainer=dunknowcoding
sentence=All-In-One, easy to use INA-series sensor library for ESP32/Arduino/Raspberry Pi Pico, examples are compatible with the monitoring tool- NiusRobotLab_INA_monitor.
paragraph=Compatibe with INA219/220/226/230/231/232/233/234/236/228/237/238/239/740X/3221/2227/4230/4235, best on ESP32, Arduino and Raspberry Pi Pico development boards, the examples match the NiusRobotLab_INA_monitor (Open Source) host software.
category=Sensors
url=https://github.com/dunknowcoding/INA_series_sensor
architectures=esp32, avr, samd, rp2040, rp2350
includes=INA_Series_Sensor.h
